/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "passport.token": [],
    "passport.authorizations.authorize": [],
    "passport.device": [],
    "passport.device.code": [],
    "passport.token.refresh": [],
    "passport.authorizations.approve": [],
    "passport.authorizations.deny": [],
    "passport.device.authorizations.authorize": [],
    "passport.device.authorizations.approve": [],
    "passport.device.authorizations.deny": [],
    "health": [],
    "oidc.discovery": [],
    "oauth.jwks": [],
    "oauth.revoke": [],
    "oauth.introspect": [],
    "oauth.userinfo": [],
    "oauth.logout": [],
    "login": [],
    "login.store": [],
    "mfa.challenge": [],
    "mfa.challenge.store": [],
    "logout": [],
    "profile.index": [],
    "profile.update": [],
    "profile.avatar": [],
    "profile.password": [],
    "profile.mfa.setup": [],
    "profile.mfa.confirm": [],
    "profile.mfa.destroy": [],
    "profile.sessions": [],
    "profile.sessions.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "profile.sessions.revoke-others": [],
    "profile.authorized-apps": [],
    "profile.authorized-apps.destroy": [
        {
            "name": "clientId",
            "required": true
        }
    ],
    "developer.clients.index": [],
    "developer.clients.store": [],
    "developer.clients.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "developer.clients.secret": [
        {
            "name": "id",
            "required": true
        }
    ],
    "developer.clients.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "dashboard": [],
    "admin.users.update-status": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.force-logout": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.audit-logs.index": [],
    "admin.application-access.index": [],
    "admin.application-access.grant-user": [
        {
            "name": "clientId",
            "required": true
        }
    ],
    "admin.application-access.grant-department": [
        {
            "name": "clientId",
            "required": true
        }
    ],
    "admin.application-access.revoke": [
        {
            "name": "clientId",
            "required": true
        },
        {
            "name": "grantId",
            "required": true
        }
    ],
    "admin.departments.index": [],
    "admin.departments.store": [],
    "admin.departments.update": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.departments.destroy": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.store": [],
    "admin.users.import.create": [],
    "admin.users.import.validate": [],
    "admin.users.import.store": [],
    "admin.users.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.force-delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.positions.assign": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.positions.terminate": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "positionId",
            "required": true
        }
    ],
    "admin.users.reset-password": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.reset-mfa": [
        {
            "name": "id",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
